# Generated by Django 2.2 on 2019-05-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owned',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='owned',
            old_name='author_id',
            new_name='author',
        ),
    ]
