# Generated by Django 2.1.1 on 2019-02-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_aka_id', models.IntegerField()),
            ],
            options={
                'db_table': 'artist_akas',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_filepath', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original', models.CharField(blank=True, max_length=128, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_level', models.IntegerField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtworks', related_query_name='theArtwork', to='bookcovers.Artists')),
            ],
            options={
                'db_table': 'artworks',
            },
        ),
        migrations.CreateModel(
            name='AuthorAkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_aka_id', models.IntegerField()),
                ('real_name', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author_akas',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_year', models.IntegerField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('quick_notes', models.CharField(blank=True, max_length=128, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theBooks', related_query_name='theBook', to='bookcovers.Authors')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('cover_id', models.AutoField(primary_key=True, serialize=False)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('cover_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('is_variant', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCovers', related_query_name='theCover', to='bookcovers.Artworks')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCovers', related_query_name='theCover', to='bookcovers.Books')),
            ],
            options={
                'db_table': 'covers',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('print_run_id', models.IntegerField(blank=True, null=True)),
                ('imprint_id', models.IntegerField(blank=True, null=True)),
                ('genre_id', models.IntegerField(blank=True, null=True)),
                ('format_id', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=20, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=50, null=True)),
                ('print_year', models.SmallIntegerField(blank=True, null=True)),
                ('purchase_year', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('currency_id', models.IntegerField(blank=True, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('designer', models.CharField(blank=True, max_length=64, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theEditions', related_query_name='theEdition', to='bookcovers.Books')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theEditions', related_query_name='theEdition', to='bookcovers.Countries')),
            ],
            options={
                'db_table': 'editions',
            },
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'formats',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='PrintRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_run_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('print', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_price', models.CharField(blank=True, max_length=255, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('print_year', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePrintRuns', related_query_name='thePrintRun', to='bookcovers.Covers')),
                ('edition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePrintRun', related_query_name='thePrintRun', to='bookcovers.Editions')),
            ],
            options={
                'db_table': 'print_runs',
            },
        ),
        migrations.AddField(
            model_name='covers',
            name='edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCover', related_query_name='theCover', to='bookcovers.Editions'),
        ),
        migrations.AddField(
            model_name='authorakas',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theAuthor_akas', related_query_name='theAuthor_aka', to='bookcovers.Authors'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtworks', related_query_name='theArtwork', to='bookcovers.Books'),
        ),
        migrations.AddField(
            model_name='artistakas',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtist_akas', related_query_name='theArtist_aka', to='bookcovers.Artists'),
        ),
        migrations.AlterUniqueTogether(
            name='printruns',
            unique_together={('print_run_id', 'order')},
        ),
    ]
