# Generated by Django 3.0.1 on 2020-02-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artbook',
            fields=[
                ('artbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'artbooks',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_filepath', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artists',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original', models.CharField(blank=True, max_length=128, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_level', models.IntegerField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtworks', related_query_name='theArtwork', to='bookcovers.Artist')),
            ],
            options={
                'db_table': 'artworks',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_year', models.IntegerField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('quick_notes', models.CharField(blank=True, max_length=128, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theBooks', related_query_name='theBook', to='bookcovers.Author')),
            ],
            options={
                'db_table': 'books',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('cover_id', models.AutoField(primary_key=True, serialize=False)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('cover_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('is_variant', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCovers', related_query_name='theCover', to='bookcovers.Artwork')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCovers', related_query_name='theCover', to='bookcovers.Book')),
            ],
            options={
                'db_table': 'covers',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('print_run_id', models.IntegerField(blank=True, null=True)),
                ('imprint_id', models.IntegerField(blank=True, null=True)),
                ('genre_id', models.IntegerField(blank=True, null=True)),
                ('format_id', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=20, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=50, null=True)),
                ('print_year', models.SmallIntegerField(blank=True, null=True)),
                ('purchase_year', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('currency_id', models.IntegerField(blank=True, null=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('designer', models.CharField(blank=True, max_length=64, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theEditions', related_query_name='theEdition', to='bookcovers.Book')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theEditions', related_query_name='theEdition', to='bookcovers.Country')),
            ],
            options={
                'db_table': 'editions',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'formats',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('imprint_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('panorama_id', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Artist')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Author')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Series')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
        migrations.CreateModel(
            name='UsedAs',
            fields=[
                ('used_as_id', models.AutoField(primary_key=True, serialize=False)),
                ('used_type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'used_as',
                'ordering': ('used_type',),
            },
        ),
        migrations.CreateModel(
            name='SetExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSetExceptions', related_query_name='theSetException', to='bookcovers.Cover')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSetExceptions', related_query_name='theSetException', to='bookcovers.Set')),
            ],
            options={
                'db_table': 'set_exceptions',
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('panorama_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('imprint_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePanoramas', related_query_name='thePanorama', to='bookcovers.Artist')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePanoramas', related_query_name='thePanorama', to='bookcovers.Author')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePanoramas', related_query_name='thePanorama', to='bookcovers.Set')),
            ],
            options={
                'db_table': 'panoramas',
            },
        ),
        migrations.AddField(
            model_name='cover',
            name='edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theCover', related_query_name='theCover', to='bookcovers.Edition'),
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theBooksSeries', related_query_name='theBooksSeries', to='bookcovers.Book')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theBooksSeries', related_query_name='theBooksSeries', to='bookcovers.Series')),
            ],
            options={
                'db_table': 'books_series',
            },
        ),
        migrations.CreateModel(
            name='AuthorAka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_aka_id', models.IntegerField()),
                ('real_name', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theAuthor_akas', related_query_name='theAuthor_aka', to='bookcovers.Author')),
            ],
            options={
                'db_table': 'author_akas',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtworks', related_query_name='theArtwork', to='bookcovers.Book'),
        ),
        migrations.CreateModel(
            name='ArtistAka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_aka_id', models.IntegerField()),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtist_akas', related_query_name='theArtist_aka', to='bookcovers.Artist')),
            ],
            options={
                'db_table': 'artist_akas',
            },
        ),
        migrations.CreateModel(
            name='ArtbookIndex',
            fields=[
                ('artbook_index_id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('book_author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artwork_year', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_year', models.CharField(blank=True, max_length=50, null=True)),
                ('artwork_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('artbook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Artbook')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Artist')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Book')),
                ('book_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Author')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Cover')),
                ('used_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.UsedAs')),
            ],
            options={
                'db_table': 'artbook_index',
            },
        ),
        migrations.AddField(
            model_name='artbook',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbooks', related_query_name='theArtbook', to='bookcovers.Artist'),
        ),
        migrations.AddField(
            model_name='artbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbooks', related_query_name='theArtbook', to='bookcovers.Author'),
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('print_run_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('print', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_price', models.CharField(blank=True, max_length=255, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('print_year', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePrintRuns', related_query_name='thePrintRun', to='bookcovers.Cover')),
                ('edition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thePrintRun', related_query_name='thePrintRun', to='bookcovers.Edition')),
            ],
            options={
                'db_table': 'print_runs',
                'unique_together': {('print_run_id', 'order')},
            },
        ),
    ]
