# Generated by Django 2.1.1 on 2019-02-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='SetExceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField()),
                ('cover_id', models.IntegerField()),
            ],
            options={
                'db_table': 'set_exceptions',
            },
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('artist_id', models.IntegerField(blank=True, null=True)),
                ('imprint_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('panorama_id', models.IntegerField(blank=True, null=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSeries', related_query_name='theSeries', to='bookcovers.Series')),
            ],
            options={
                'db_table': 'sets',
            },
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('name',)},
        ),
    ]
