# Generated by Django 2.1.1 on 2018-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covers',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
    ]
