# Generated by Django 2.2 on 2019-05-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0002_auto_20190521_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbookindex',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Book'),
        ),
        migrations.AddField(
            model_name='artbookindex',
            name='book_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Author'),
        ),
        migrations.AddField(
            model_name='artbookindex',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Cover'),
        ),
    ]
