# Generated by Django 2.1.1 on 2018-10-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0002_covers_is_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_aka_id', models.IntegerField()),
                ('realname', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_akas', to='bookcovers.Authors')),
            ],
            options={
                'db_table': 'author_akas',
            },
        ),
    ]
