# Generated by Django 2.1.1 on 2019-02-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0002_auto_20190208_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='sets',
            name='author_id',
        ),
        migrations.AddField(
            model_name='sets',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Artists'),
        ),
        migrations.AddField(
            model_name='sets',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Authors'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theSets', related_query_name='theSet', to='bookcovers.Series'),
        ),
    ]
