# Generated by Django 2.2 on 2019-05-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0003_auto_20190521_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='artbookindex',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Artist'),
        ),
        migrations.AlterField(
            model_name='artbookindex',
            name='artbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.Artbook'),
        ),
    ]
