# Generated by Django 2.1.1 on 2019-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0003_auto_20190217_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_series',
            },
        ),
    ]
