# Generated by Django 2.2 on 2019-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0004_auto_20190527_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbookindex',
            name='artwork_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
