# Generated by Django 2.1.1 on 2018-10-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0004_auto_20181014_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorakas',
            old_name='realname',
            new_name='real_name',
        ),
    ]
