# Generated by Django 3.0.1 on 2021-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0004_auto_20201209_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='confidence_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'Highly likely'), (3, 'Maybe'), (4, 'Not really'), (5, 'No')], default=1, null=True),
        ),
    ]
