# Generated by Django 3.0.1 on 2021-08-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0005_auto_20210425_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbookindex',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('artbookIndex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theLinks', related_query_name='theLink', to='bookcovers.ArtbookIndex')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theLinks', related_query_name='theLink', to='bookcovers.Artwork')),
            ],
            options={
                'db_table': 'links',
            },
        ),
    ]
