# Generated by Django 2.2 on 2019-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0005_artbookindex_artwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbookindex',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
