# Generated by Django 2.1.1 on 2018-11-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0005_auto_20181014_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editions',
            name='country_id',
        ),
        migrations.AddField(
            model_name='editions',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookcovers.Countries'),
        ),
        migrations.AlterField(
            model_name='artworks',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artworks', related_query_name='artwork', to='bookcovers.Books'),
        ),
        migrations.AlterField(
            model_name='authorakas',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_akas', related_query_name='author_aka', to='bookcovers.Authors'),
        ),
    ]
