# Generated by Django 2.1.1 on 2018-12-02 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0006_auto_20181129_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allEditions', related_query_name='theEdition', to='bookcovers.Countries'),
        ),
    ]
