# Generated by Django 2.2 on 2019-06-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0007_auto_20190531_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedAs',
            fields=[
                ('used_as_id', models.AutoField(primary_key=True, serialize=False)),
                ('used_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'used_as',
            },
        ),
        migrations.AddField(
            model_name='artbookindex',
            name='used_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theArtbookIndexes', related_query_name='theArtbookIndex', to='bookcovers.UsedAs'),
        ),
    ]
