# Generated by Django 2.2 on 2019-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcovers', '0008_auto_20190605_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedas',
            name='used_type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
